public enum StatsType : byte
{
    STR = 0,
    END = 1,
    DEX = 2,
    INT = 3,
    SPR = 5,
    Damage_Min = 6,
    Damage_Max = 7,
    Defense = 8,
    Aim = 9,
    Evasion = 10,
    MagicDamage_Min = 11,
    MagicDamage_Max = 12,
    MagicDefense = 13,
    MaxHP = 16,
    MaxSP = 17,
    Bonus_Damage = 18,
    Bonus_Defense = 19,
    Bonus_MagicDamage = 20,
    Bonus_MagicDefense = 21,
    Bonus_Aim = 22,
    Bonus_Evasion = 23,
    CriticalRate = 24,
    BlockRate = 25,
    Bonus_MaxHP = 26,
    Bonus_MaxSP = 27,
    MaxLP = 36,//crusader stuff :D
}