namespace DFEngine.Network
{
	public enum NetworkConnectionType
	{
		NCT_DB_ACCOUNT = 0,
		NCT_DB_ACCOUNTLOG = 1,
		NCT_DB_CHARACTER = 2,
		NCT_DB_GAMELOG = 3,
		NCT_LOGIN = 4,
		NCT_WORLDMANAGER = 5,
		NCT_ZONE = 6,
		NCT_PATCH = 7,
		NCT_OPTOOL = 8,
		NCT_WEB = 9,
		NCT_CLIENT = 20,
		NCT_MAXNETWORKCONNECTIONCLIENTTYPE = 21
	}
}
