namespace DFEngine.Content.Items
{
	public enum ItemEquip
	{
		ITEMEQUIP_NONE = 0x0,
		ITEMEQUIP_HAT = 0x1,
		ITEMEQUIP_HATACC_C = 0x2,
		ITEMEQUIP_NOUSE01 = 0x3,
		ITEMEQUIP_NOUSE02 = 0x4,
		ITEMEQUIP_FACETATTOO = 0x5,
		ITEMEQUIP_NECKLACE = 0x6,
		ITEMEQUIP_BODY = 0x7,
		ITEMEQUIP_BODYACC = 0x8,
		ITEMEQUIP_BACK = 0x9,
		ITEMEQUIP_LEFTHAND = 0xA,
		ITEMEQUIP_LEFTHANDACC = 0xB,
		ITEMEQUIP_RIGHTHAND = 0xC,
		ITEMEQUIP_RIGHTHANDACC = 0xD,
		ITEMEQUIP_BRACELET = 0xE,
		ITEMEQUIP_LEFTRING = 0xF,
		ITEMEQUIP_RIGHTRING = 0x10,
		ITEMEQUIP_BELT = 0x11,
		ITEMEQUIP_TAIL = 0x12,
		ITEMEQUIP_LEG = 0x13,
		ITEMEQUIP_LEGACC = 0x14,
		ITEMEQUIP_SHOES = 0x15,
		ITEMEQUIP_SHOESACC = 0x16,
		ITEMEQUIP_EARRING = 0x17,
		ITEMEQUIP_MOUTH = 0x18,
		ITEMEQUIP_SHOULDER_B = 0x19,
		ITEMEQUIP_EYE = 0x1A,
		ITEMEQUIP_HATACC = 0x1B,
		ITEMEQUIP_MINIMON = 0x1C,
		ITEMEQUIP_SHIELDACC = 0x1D,
		MAX_ITEMEQUIP = 0x1D
	}
}