//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AccountEntity : DbContext
    {
        public AccountEntity()
            : base("name=AccountEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<IPBlock> IPBlocks { get; set; }
        public virtual DbSet<RegionServer> RegionServers { get; set; }
        public virtual DbSet<Version> Versions { get; set; }
        public virtual DbSet<WorldList> WorldLists { get; set; }
    }
}
