//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character_Options
    {
        public int ID { get; set; }
        public byte[] ShortCutData { get; set; }
        public byte[] ShortCutSize { get; set; }
        public byte[] Video { get; set; }
        public byte[] Sound { get; set; }
        public byte[] Game { get; set; }
        public byte[] WindowsPos { get; set; }
        public byte[] KeyMapping { get; set; }
    }
}
