//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character_Options
    {
        public int ID { get; set; }
        public byte[] ShortCutData { get; set; }
        public byte[] ShortCutSize { get; set; }
        public byte[] Video { get; set; }
        public byte[] Sound { get; set; }
        public byte[] Game { get; set; }
        public byte[] WindowsPos { get; set; }
        public byte[] KeyMapping { get; set; }
    }
}
