//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBCharacter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DBCharacter()
        {
            this.Items = new HashSet<DBItem>();
            this.Friends = new HashSet<DBFriend>();
        }
    
        public int ID { get; set; }
        public int AccountID { get; set; }
        public string Name { get; set; }
        public byte Slot { get; set; }
        public Nullable<short> Map { get; set; }
        public int PositionX { get; set; }
        public int PositionY { get; set; }
        public byte Rotation { get; set; }
        public byte Class { get; set; }
        public byte Level { get; set; }
        public int HP { get; set; }
        public int SP { get; set; }
        public short HPStones { get; set; }
        public short SPStones { get; set; }
        public long EXP { get; set; }
        public long Money { get; set; }
        public int Fame { get; set; }
        public int KillPoints { get; set; }
        public bool IsMale { get; set; }
        public byte Hair { get; set; }
        public byte HairColor { get; set; }
        public byte Face { get; set; }
        public byte FreeStat_Points { get; set; }
        public byte FreeStat_Str { get; set; }
        public byte FreeStat_End { get; set; }
        public byte FreeStat_Dex { get; set; }
        public byte FreeStat_Int { get; set; }
        public byte FreeStat_Spr { get; set; }
        public byte SkillPoints { get; set; }
        public System.DateTime LastLogin { get; set; }
        public bool IsOnline { get; set; }
        public bool IsFirstLogin { get; set; }
        public int LP { get; set; }
        public int FriendPoints { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBItem> Items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DBFriend> Friends { get; set; }
    }
}
