//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBFriend
    {
        public int OwnerID { get; set; }
        public int FriendID { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual DBCharacter Character { get; set; }
    }
}
