//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DBItem
    {
        public long ItemKey { get; set; }
        public byte StorageType { get; set; }
        public int Owner { get; set; }
        public short Storage { get; set; }
        public int ItemID { get; set; }
        public int Flags { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual ItemOption ItemOption { get; set; }
        public virtual DBCharacter Character { get; set; }
    }
}
