//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoldSpammer
    {
        public int ReporterID { get; set; }
        public string ReporterIP { get; set; }
        public int SpammerID { get; set; }
        public string SpammerIP { get; set; }
        public System.DateTime ReportDate { get; set; }
    }
}
