//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guild
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public byte[] Password { get; set; }
        public bool AllowGuildWar { get; set; }
        public string Message { get; set; }
        public System.DateTime MessageCreateDate { get; set; }
        public int MessageCreaterID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long Money { get; set; }
    }
}
