//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionServer
    {
        public byte Region { get; set; }
        public string ListenerIP { get; set; }
        public int Port { get; set; }
        public int WorkThreadCount { get; set; }
    }
}
