//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public long ID { get; set; }
        public int OwnerID { get; set; }
        public short SkillID { get; set; }
        public bool IsPassive { get; set; }
        public byte[] Upgrades { get; set; }
    }
}
