//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public long ID { get; set; }
        public int OwnerID { get; set; }
        public int TitleType { get; set; }
        public byte TitleLevel { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public bool IsActive { get; set; }
        public long Data { get; set; }
    }
}
