//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorldList
    {
        public int ID { get; set; }
        public string WorldName { get; set; }
        public bool TestServer { get; set; }
        public string AllowIP { get; set; }
        public byte Region { get; set; }
    }
}
