//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragonFiesta.Database.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldEntity : DbContext
    {
        public WorldEntity()
            : base("name=WorldEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BlockList> BlockLists { get; set; }
        public virtual DbSet<Buff> Buffs { get; set; }
        public virtual DbSet<Character_Options> Character_Options { get; set; }
        public virtual DbSet<DBCharacter> DBCharacters { get; set; }
        public virtual DbSet<GoldSpammer> GoldSpammers { get; set; }
        public virtual DbSet<GroupMember> GroupMembers { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GuildMember> GuildMembers { get; set; }
        public virtual DbSet<Guild> Guilds { get; set; }
        public virtual DbSet<ItemOption> ItemOptions { get; set; }
        public virtual DbSet<DBItem> DBItems { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<DBFriend> DBFriends { get; set; }
    }
}
