public enum GameSettingType : ushort
{
    SHOW_MY_CHAR_NAME = 0,

    SHOW_OTHERS_CHAR_NAME = 1,

    SHOW_NPC_NAME = 2,

    SHOW_MONSTER_NAME = 3,

    SHOW_ITEM_NAME = 4,

    SHOW_HP_BAR = 5,

    SHOW_SP_BAR = 6,

    SHOW_INTERFACE = 7,

    SHOW_SPEECH_BUBBLE = 8,

    SHOW_BILLBOARD_NAMEPANEL = 9,

    SHOW_BASICINFO_TIP = 10,

    SHOW_PLAYGUIDE = 11,

    REFUSE_WHISPER = 12,

    REFUSE_TRADE = 13,

    REFUSE_PARTY_INVITE = 14,

    REFUSE_GUILD_INVITE = 15,

    REFUSE_SYSTEM_MSG = 16,

    REFUSE_CONFIRM_MSG = 17,

    AUTOHIDE_SYSTEMWIN = 18,

    AUTOHIDE_CHATWIN = 19,

    NOTICE_LOGIN_GUILDMEMBER = 20,

    START_CHATTING_ENTER = 21,

    INIT_INTERFACEPOS = 22,

    ENABLE_SKILLLOCK = 23,

    SHOW_AUTOSTACK = 27,

    SHINE_GAME_OPT_MAX = 28,
}