namespace DragonFiesta.Providers.Items
{
    public enum AuctionGroupType : uint
    {
        AG_ALL = 0,
        AG_M_WEAPON = 1,
        AG_M_ARMOR = 2,
        AG_M_ACCESSORY = 3,
        AG_M_PRODUCE = 4,
        AG_M_ENCHANT = 5,
        AG_M_RAW = 6,
        AG_M_ETC = 7,
        AG_S_ONEHANDSWORD = 8,
        AG_S_TWOHANDSWORD = 9,
        AG_S_AXE = 0xA,
        AG_S_MACE = 0xB,
        AG_S_HAMMER = 0xC,
        AG_S_BOW = 0xD,
        AG_S_CBOW = 0xE,
        AG_S_STAFF = 0xF,
        AG_S_WAND = 0x10,
        AG_S_CLAW = 0x11,
        AG_S_DSWORD = 0x12,
        AG_S_FIGHTER = 0x13,
        AG_S_CLERIC = 0x14,
        AG_S_ARCHER = 0x15,
        AG_S_MAGE = 0x16,
        AG_S_JOKER = 0x17,
        AG_S_NECK = 0x18,
        AG_S_EARRING = 0x19,
        AG_S_RING = 0x1A,
        AG_S_SCROLL = 0x1B,
        AG_S_POTION = 0x1C,
        AG_S_STONE = 0x1D,
        AG_S_FOOD = 0x1E,
        AG_S_ENCHANT = 0x1F,
        AG_S_PRODRAW = 0x20,
        AG_S_FARM = 0x21,
        AG_S_MOVER = 0x22,
        AG_S_MINIHOUSE = 0x23,
        AG_S_COSTUME = 0x24,
        AG_S_ABILLITY = 0x25,
        AG_S_EMOTION = 0x26,
        AG_S_ETC = 0x27,
        AG_S_BLADE = 0x28,
        AG_S_SENTINEL = 0x29,
        AG_S_BRACELET = 0x2A
    }
}
